# Generated by Django 3.0.3 on 2020-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200224_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='images/category.jpg', null=True, upload_to='songs', verbose_name='分类图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs', verbose_name='歌曲文件'),
        ),
    ]
