# Generated by Django 2.1 on 2020-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200224_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='', max_length=10, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='个人描述'),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='nickname',
            field=models.CharField(default='静听用户', max_length=10, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='category/default.jpg', null=True, upload_to='category', verbose_name='分类图片'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='files/default.mp3', upload_to='files', verbose_name='歌曲文件'),
        ),
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(blank=True, default='imgs/default.jpg', null=True, upload_to='imgs', verbose_name='歌曲图片'),
        ),
        migrations.AlterField(
            model_name='usermanager',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='账号'),
        ),
    ]
