# Generated by Django 2.1 on 2020-02-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200225_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='song',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(default='佚名', max_length=10, verbose_name='作者'),
        ),
    ]
