# Generated by Django 2.1 on 2020-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200225_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='img',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users', verbose_name='用户头像'),
        ),
    ]
