# Generated by Django 2.1 on 2020-02-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200226_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Song', verbose_name='歌曲'),
        ),
    ]
