# Generated by Django 2.1 on 2020-02-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200226_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='收藏时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserManager', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论收藏管理',
                'verbose_name_plural': '评论收藏管理',
            },
        ),
    ]
