# Generated by Django 3.1.6 on 2021-03-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200227_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='broadcast',
            field=models.IntegerField(default=2044, verbose_name='播放数量'),
        ),
    ]
